package Day3;

import java.util.Set;

import org.openqa.selenium.By;
import org.openqa.selenium.chrome.ChromeDriver;

public class getMethods {

	public static void main(String[] args) throws InterruptedException  {
	
		
		ChromeDriver driver =new ChromeDriver();
		
		driver.manage().window().maximize(); //use for maximize the browser window
		
		//get method
		driver.get("https://opensource-demo.orangehrmlive.com/web/index.php/auth/login");
	
		//getTitle()
	//System.out.println("The title of page is " +driver.getTitle());	
	
	//getCurrentURL()
	
//	String url=driver.getCurrentUrl();
//	System.out.println("The url of the page is " +url);
//	
	// getpagesource()
	
	//String ps=driver.getPageSource();
	//System.out.println("The HTML code " + ps);
	//System.out.println(ps.contains("html"));
	
		//getWindowHandle() return the window id i.e generated by browser automatically
		
	//	System.out.println("The window id is :" +driver.getWindowHandle());
		//99A0271E9C43E1A49D90C20F50E661A7
		//512D0D3F5062BCF5D75703A42427522A
		
		Thread.sleep(5000);
		driver.findElement(By.xpath("//a[normalize-space()='OrangeHRM, Inc']")).click();
		//getWindowHandles()
		
		Set<String> windowids =driver.getWindowHandles();
		
		for(String wid:windowids)
		{
		System.out.println("the window ids are " +wid);
		
		}
		
		
	
	driver.close();
	
}
}